### ISSUE TITLE
Doesn't Retain Font Family

### ISSUE THREAD

**Issue by tridnguyen** [Ayushmaan0101/Ice-Theme#1]
Thanks for the theme it's great, but there's an issue where it keeps reverting the font family to `Monaco`, `Consolas`. Is this intentional? I set my font to `Victor Mono` in the settings.json, but it keeps getting reverted by this theme. If I disable the ice theme, the issue goes away.

Actually, just noticed it is by design,  

```
vscode.workspace.getConfiguration().update("editor.fontFamily", "Monaco, Consolas, 'Courier New', monospace", vscode.ConfigurationTarget.Global);
```

**Comment by ayushmxxn** [comment]
> Thanks for the theme it's great, but there's an issue where it keeps reverting the font family to `Monaco`, `Consolas`. Is this intentional? I set my font to `Victor Mono` in the settings.json, but it keeps getting reverted by this theme. If I disable the ice theme, the issue goes away.
> 
> Actually, just noticed it is by design,
> 
> ```
> vscode.workspace.getConfiguration().update("editor.fontFamily", "Monaco, Consolas, 'Courier New', monospace", vscode.ConfigurationTarget.Global);
> ```

Thank you for bringing this to my attention. I will make sure to address this issue and improve the font handling in a better way.
